# Generated by Django 4.2.1 on 2023-05-18 17:43

from django.db import migrations, models
import scheduler_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, upload_to=scheduler_app.models.event_image, verbose_name='Tiff image')),
            ],
        ),
    ]
