# Generated by Django 4.2.1 on 2023-05-18 18:16

from django.db import migrations, models
import scheduler_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(upload_to=scheduler_app.models.event_image, verbose_name='Tiff image'),
        ),
    ]
